config/routes.rb
Rails.application.routes.draw do
  
devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
  
  root to: "public/homes#top"
  get 'about' => 'public/homes#about', as: 'about'

  get 'unsubscribe' => 'public/customers#unsubscribe'
  patch 'customers/withdraw' => 'public/customers#withdraw', as: 'withdraw'



  get 'admin' => 'admin/homes#top'

  namespace :public do

    # devise_for :customers
    get "about" => "homes#about"
    resources :items, only: [:index,:show]
    delete 'cart_items/all_destroy'=>'cart_items#all_destroy',as: 'all_destroy'
    resources :cart_items, only: [:index,:update,:destroy,:create]
    post "orders/confirm" => "orders#confirm", as: "confirm"
    get "complete" => "orders#complete", as: "complete"
    resources :orders, only: [:new,:create,:index,:show]
    resources :deliveries, only: [:index,:edit,:create,:update,:destroy]
    resource :customers, only: [:show,:edit,:update]
    resources :sessions, only: [:new,:create,:destroy]
    resources :addresses, only: [:index, :edit,  :create, :update, :destroy]
  end
  namespace :admin do

    resources :genres, only: [:index,:create,:edit,:update]
    resources :customers, only: [:index,:show,:edit,:update]
    resources :orders, only: [:show,:update]
    resources :orders_status, only: [:update]
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
  end

end


    #namespace :public do
   # get 'deliveries/index'
    #get 'deliveries/edit'
    #get 'deliveries/create'
    #get 'deliveries/update'
   # get 'deliveries/destroy'
  #end
  #namespace :public do
    #get 'orders/new'
   # get 'orders/confirm'
   # get 'orders/complete'
    #get 'orders/create'
    #get 'orders/index'
    #get 'orders/show'
  #end
  #namespace :public do
    #get 'cart_items/index'
    #get 'cart_items/update'
    #get 'cart_items/destroy'
    #get 'cart_items/all_destroy'
    #get 'cart_items/create'
  #end
  #namespace :public do
    #get 'customers/show'
    #get 'customers/edit'
    #get 'customers/update'
    #get 'customers/unsubscribe'
    #get 'customers/withdraw'
  #end
  #namespace :public do
    #get 'sessions/new'
    #get 'sessions/create'
    #get 'sessions/destroy'
  #end
  #namespace :public do
    #get 'registrations/new'
   # get 'registrations/create'
  #end
  #namespace :public do
    #get 'items/index'
    #get 'items/show'
  #end

  #namespace :admin do
    #get 'orders/show'
    #get 'orders/update'
  #end
  #namespace :admin do
   # get 'customers/index'
    #get 'customers/show'
    #get 'customers/edit'
    #get 'customers/update'
  #end
  #namespace :admin do
    #get 'genres/index'
    #get 'genres/create'
    #get 'genres/edit'
    #get 'genres/update'
  #end
  #namespace :admin do
   # get 'items/index'
   # get 'items/new'
   # get 'items/create'
   # get 'items/show'
   # get 'items/edit'
    #get 'items/update'
  #end
 # namespace :admin do
   # get 'homes/top'
  #end
  #namespace :admin do
    #get 'sessions/new'
    #get 'sessions/create'
    #get 'sessions/destroy'
  #end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :order_details
  belongs_to :genre, optional: true

# 画像投稿
  has_one_attached :image

  validates :name, {presence: true}
  validates :introduction, {presence: true}
  validates :price, {presence: true}
  
  def add_tax_price
    (self.price * 1.1).round
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    # @items = Item.page(params[:page]).per(10)
    @items = Item.all
    
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    # @item.user_id = current_user.id
    if @item.save!
      redirect_to admin_items_path(@item)
    else
      render "new"
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
      if @item.update(item_params)
        redirect_to admin_item_path(@item.id)
      else
        render "edit"
      end
  end

    private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active )
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/create.html.erb
<h1>Admin::Items#create</h1>
<p>Find me in app/views/admin/items/create.html.erb</p>

app/views/admin/items/edit.html.erb
<!--<h1>Admin::Items#edit</h1>-->
<!--<p>Find me in app/views/admin/items/edit.html.erb</p>-->




<!--https://qiita.com/japwork/items/e258ccbbe4f48ea5a3b5-->
<!--config/routes.rb書きかえるかも-->
<!--patch 'admin/items/:id' => 'admin/items#update', as: 'update_admin_item'-->
          <%#= form_with model: @item, url: admin_item_path(@item), method: :patch, do |f| %>
          <%= form_for(@item, url: admin_item_path) do |f| %>
            <h5>商品画像</h5>
              <%= f.file_field :image, accept: "image/*" %>
            <h5>お名前</h5>
              <%= f.text_field :name %>
            <h5>紹介文</h5>
              <%= f.text_area :introduction %>
            <h5>指名価格</h5>
              <%= f.text_field :price, autofocus: true %>
            <h5>本日のシフト</h5>
              <%= f.select :is_active, ["出勤中", "お休み"] %>
            
            <div><%= f.submit :変更を保存, class: "btn btn-primary" %></div>
            
          <% end %>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <h3 class="page-name col-lg-2">商品一覧</h3>
    <div class="col-lg-8"></div>
    <div class="col-lg-1">
      <a href="/admin/items/new" class="bottom"><i class="fas fa-plus-circle"></i></a>
    </div>
  </div>

  <div class="row">
    <table class="table table-hover table-inverse col-md-12 px-auto">
      <thead>
        <tr>
          <th>人気ランキング</th>
          <th>お名前</th>
          <th>指名価格</th>
          <th>本日のシフト</th>
        </tr>
      </thead>

      <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td>
            <%= link_to admin_item_path(item.id) do %>
            <span><%= item.name %></span>
            <% end %>
          </td>
          <td><%= item.price %></td>
          <td>
            <%#= item.is_active %>
            <% if item.is_active = false %>
              <p>お休み</p>
            <% else %>
              <P>出勤中</P>
            <% end %>
          </td>
          
        </tr>
      <% end %>
      </tbody>
    </table>
    <div class="paginate mx-auto">
      <%#= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<!--<h1>Admin::Items#new</h1>-->
<!--<p>Find me in app/views/admin/items/new.html.erb</p>-->

<div class="container">
  <div class="row">
    

      <%= form_with model: @item, url: '/admin/items', method: :post do |f| %>
        <h5>商品画像</h5>
          <%= f.file_field :image, accept: "image/*" %>

    

            <h5>お名前</h5>
              <%= f.text_field :name %>
            <h5>紹介文</h5>
              <%= f.text_area :introduction %>
            <h5>指名価格</h5>
              <%= f.text_field :price, autofocus: true %>
            <h5>本日のシフト</h5>
              <%= f.select :is_active, ["出勤中", "お休み"] %>
            <%= f.submit '新規登録', class: "btn btn-primary" %>
            
          <% end %>


  </div>
</div>

app/views/admin/items/show.html.erb
<!--<h1>Admin::Items#show</h1>-->
<!--<p>Find me in app/views/admin/items/show.html.erb</p>-->


          <div class="container">
            <!--<h2>商品詳細</h2><br>-->
              <div class="row">
                  <div class="col-xs-4">
                    <% if @item.image.attached? %>
                      <%= image_tag @item.image, size: "300x300" %>
                    <% else %>
                      <%= image_tag 'no_image', size: "300x300" %>
                    <% end %>
                  </div>
              </div>
          </div>
          
          
          
              
            <div class="col-xs-8">
              
                <h5>お名前
                  <%= @item.name %>
                </h5>
              
              
              <!--<div>-->
                <h5>紹介文
                  <%= @item.introduction %>
                </h5>
              <!--</div>-->
              
              <!--<div>-->
              <!--</div>-->
              
              <!--<div>-->
                <h5>指名価格
                  <%= @item.price %>円
                </h5>
              <!--</div>-->
              
              <!--<div>-->
                <h5>本日のシフト
                <!--  <%#= @item.is_active,  %>-->
                <td class="td-statu">
              
                <% if @item.is_active = false %>
                  
                  <p>お休み</p>
                  
                  <% else %>
                  
                  <P>出勤中</P>
                  
                  <% end %>
                </h5>
              <!--</div>-->
              
            </div>
              
              <%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-primary", style: "margin: 0 auto;" %>
              

app/views/admin/items/update.html.erb
<h1>Admin::Items#update</h1>
<p>Find me in app/views/admin/items/update.html.erb</p>