config/routes.rb
Rails.application.routes.draw do
  
devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
  
  root to: "public/homes#top"
  get 'about' => 'public/homes#about', as: 'about'

  get 'unsubscribe' => 'public/customers#unsubscribe'
  patch 'customers/withdraw' => 'public/customers#withdraw', as: 'withdraw'



  get 'admin' => 'admin/homes#top'

  namespace :public do

    # devise_for :customers
    get "about" => "homes#about"
    resources :items, only: [:index,:show]
    delete 'cart_items/all_destroy'=>'cart_items#all_destroy',as: 'all_destroy'
    resources :cart_items, only: [:index,:update,:destroy,:create]
    post "orders/confirm" => "orders#confirm", as: "confirm"
    get "complete" => "orders#complete", as: "complete"
    resources :orders, only: [:new,:create,:index,:show]
    resources :deliveries, only: [:index,:edit,:create,:update,:destroy]
    resource :customers, only: [:show,:edit,:update]
    resources :sessions, only: [:new,:create,:destroy]
    resources :addresses, only: [:index, :edit,  :create, :update, :destroy]
  end
  namespace :admin do

    resources :genres, only: [:index,:create,:edit,:update]
    resources :customers, only: [:index,:show,:edit,:update]
    resources :orders, only: [:show,:update]
    resources :orders_status, only: [:update]
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
  end

end


    #namespace :public do
   # get 'deliveries/index'
    #get 'deliveries/edit'
    #get 'deliveries/create'
    #get 'deliveries/update'
   # get 'deliveries/destroy'
  #end
  #namespace :public do
    #get 'orders/new'
   # get 'orders/confirm'
   # get 'orders/complete'
    #get 'orders/create'
    #get 'orders/index'
    #get 'orders/show'
  #end
  #namespace :public do
    #get 'cart_items/index'
    #get 'cart_items/update'
    #get 'cart_items/destroy'
    #get 'cart_items/all_destroy'
    #get 'cart_items/create'
  #end
  #namespace :public do
    #get 'customers/show'
    #get 'customers/edit'
    #get 'customers/update'
    #get 'customers/unsubscribe'
    #get 'customers/withdraw'
  #end
  #namespace :public do
    #get 'sessions/new'
    #get 'sessions/create'
    #get 'sessions/destroy'
  #end
  #namespace :public do
    #get 'registrations/new'
   # get 'registrations/create'
  #end
  #namespace :public do
    #get 'items/index'
    #get 'items/show'
  #end

  #namespace :admin do
    #get 'orders/show'
    #get 'orders/update'
  #end
  #namespace :admin do
   # get 'customers/index'
    #get 'customers/show'
    #get 'customers/edit'
    #get 'customers/update'
  #end
  #namespace :admin do
    #get 'genres/index'
    #get 'genres/create'
    #get 'genres/edit'
    #get 'genres/update'
  #end
  #namespace :admin do
   # get 'items/index'
   # get 'items/new'
   # get 'items/create'
   # get 'items/show'
   # get 'items/edit'
    #get 'items/update'
  #end
 # namespace :admin do
   # get 'homes/top'
  #end
  #namespace :admin do
    #get 'sessions/new'
    #get 'sessions/create'
    #get 'sessions/destroy'
  #end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/customer.rb
class Customer < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :cart_items, dependent: :destroy
         has_many :orders, dependent: :destroy
         has_many :addresses, dependent: :destroy

    # 退会機能
    def active_for_authentication?
      super && (self.is_deleted == false)
    end

       validates :last_name,  presence: true
       validates :first_name, presence: true
       validates :last_name_kana,  presence: true
       validates :first_name_kana, presence: true
       validates :telephone_number, presence: true
       validates :postal_code,  presence: true
       validates :address, presence: true
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  
  before_action :authenticate_admin!
  
  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customers_path
  end

    private

    def customer_params
        params.require(:customer).permit(:first_name, :last_name, :last_name_kana,
                                         :first_name_kana, :email, :encrypted_password,
                                         :postal_code, :address, :telephone_number,
                                         :is_deleted)
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container px-5 px-sm-0">
  <h1><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h1>
  <div class="row">
    <div class="col-lg-8">
      <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |f| %>
        <table class="table table-borderless">
        <thead>
          <tr>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th>会員ID</th>
            <th><%= @customer.id %></th>
          </tr>
          <tr>
            <th>氏名</th>
            <th><%= f.text_field :last_name %> <%= f.text_field :first_name %></th>
          </tr>
          <tr>
            <th>フリガナ</th>
            <th><%= f.text_field :last_name_kana %> <%= f.text_field :first_name_kana %></th>
          </tr>
          <tr>
            <th>郵便番号</th>
            <th><%= f.text_field :postal_code %></th>
          </tr>
          <tr>
            <th>住所</th>
            <th><%= f.text_field :address %></th>
          </tr>
          <tr>
            <th>電話番号</th>
            <th><%= f.text_field :telephone_number %></th>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <th><%= f.text_field :email %></th>
          </tr>
          <tr>
            <th>会員ステータス</th>
            <th><%= f.radio_button :is_deleted, false %>
                <%= f.label :is_deleted, "有効" %>
                <%= f.radio_button :is_deleted, true %>
                <%= f.label :is_deleted, "無効" %>
            </th>
          </tr>
        </tbody>
      </table>
      <%= f.submit "変更を保存", class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <h3 class="page-name">会員一覧</h3>
  </div>

  <div class="row">
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td>
            <%= link_to admin_customer_path(customer.id) do %>
              <p><%= customer.first_name %><%= customer.last_name %></p>
            <% end %>
          </td>
          <td><%= customer.email %></td>
          <td>
            <% if customer.is_deleted %>
              <p>退会</p>
            <% else %>
              <p>有効</p>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="row">
    <div class="px-auto">
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <h3 class="page-name">
      <strong>
        <%= @customer.first_name %><%= @customer.last_name %>
      </strong>
        さんの
      <strong>
        会員詳細
      </strong>
    </h3>
  </div>

  <div class="row">
    <div class="col-lg-10">
      <table>
        <tr>
          <th>会員ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th>氏名</th>
          <td><%= @customer.first_name %><%= @customer.last_name %></td>
        </tr>
        <tr>
          <th>フリガナ</th>
          <td><%= @customer.first_name_kana %><%= @customer.last_name_kana %></td>
        </tr>
        <tr>
          <th>郵便番号</th>
          <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= @customer.telephone_number %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <th>会員ステータス</th>
          <td><% if @customer.is_deleted == false %>
                <p>退会</p>
              <% else %>
                <p>有効</p>
              <% end %>
          </td>
        </tr>
        <tr>
          <th></th>
          <td>
            <%= link_to edit_admin_customer_path(@customer) , class: 'btn btn-success' do %>
              <span>編集する</span>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>

</div>

app/views/admin/customers/update.html.erb
<h1>Admin::Customers#update</h1>
<p>Find me in app/views/admin/customers/update.html.erb</p>