config/routes.rb
Rails.application.routes.draw do
  
devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
  
  root to: "public/homes#top"
  get 'about' => 'public/homes#about', as: 'about'

  get 'unsubscribe' => 'public/customers#unsubscribe'
  patch 'customers/withdraw' => 'public/customers#withdraw', as: 'withdraw'



  get 'admin' => 'admin/homes#top'

  namespace :public do

    # devise_for :customers
    get "about" => "homes#about"
    resources :items, only: [:index,:show]
    delete 'cart_items/all_destroy'=>'cart_items#all_destroy',as: 'all_destroy'
    resources :cart_items, only: [:index,:update,:destroy,:create]
    post "orders/confirm" => "orders#confirm", as: "confirm"
    get "complete" => "orders#complete", as: "complete"
    resources :orders, only: [:new,:create,:index,:show]
    resources :deliveries, only: [:index,:edit,:create,:update,:destroy]
    resource :customers, only: [:show,:edit,:update]
    resources :sessions, only: [:new,:create,:destroy]
    resources :addresses, only: [:index, :edit,  :create, :update, :destroy]
  end
  namespace :admin do

    resources :genres, only: [:index,:create,:edit,:update]
    resources :customers, only: [:index,:show,:edit,:update]
    resources :orders, only: [:show,:update]
    resources :orders_status, only: [:update]
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
  end

end


    #namespace :public do
   # get 'deliveries/index'
    #get 'deliveries/edit'
    #get 'deliveries/create'
    #get 'deliveries/update'
   # get 'deliveries/destroy'
  #end
  #namespace :public do
    #get 'orders/new'
   # get 'orders/confirm'
   # get 'orders/complete'
    #get 'orders/create'
    #get 'orders/index'
    #get 'orders/show'
  #end
  #namespace :public do
    #get 'cart_items/index'
    #get 'cart_items/update'
    #get 'cart_items/destroy'
    #get 'cart_items/all_destroy'
    #get 'cart_items/create'
  #end
  #namespace :public do
    #get 'customers/show'
    #get 'customers/edit'
    #get 'customers/update'
    #get 'customers/unsubscribe'
    #get 'customers/withdraw'
  #end
  #namespace :public do
    #get 'sessions/new'
    #get 'sessions/create'
    #get 'sessions/destroy'
  #end
  #namespace :public do
    #get 'registrations/new'
   # get 'registrations/create'
  #end
  #namespace :public do
    #get 'items/index'
    #get 'items/show'
  #end

  #namespace :admin do
    #get 'orders/show'
    #get 'orders/update'
  #end
  #namespace :admin do
   # get 'customers/index'
    #get 'customers/show'
    #get 'customers/edit'
    #get 'customers/update'
  #end
  #namespace :admin do
    #get 'genres/index'
    #get 'genres/create'
    #get 'genres/edit'
    #get 'genres/update'
  #end
  #namespace :admin do
   # get 'items/index'
   # get 'items/new'
   # get 'items/create'
   # get 'items/show'
   # get 'items/edit'
    #get 'items/update'
  #end
 # namespace :admin do
   # get 'homes/top'
  #end
  #namespace :admin do
    #get 'sessions/new'
    #get 'sessions/create'
    #get 'sessions/destroy'
  #end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

  def address_display
  '〒' + post_code + ' ' + address_code + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true
  
  def subtotal
    item.add_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :cart_items, dependent: :destroy
         has_many :orders, dependent: :destroy
         has_many :addresses, dependent: :destroy

    # 退会機能
    def active_for_authentication?
      super && (self.is_deleted == false)
    end

       validates :last_name,  presence: true
       validates :first_name, presence: true
       validates :last_name_kana,  presence: true
       validates :first_name_kana, presence: true
       validates :telephone_number, presence: true
       validates :postal_code,  presence: true
       validates :address, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :order_details
  belongs_to :genre, optional: true

# 画像投稿
  has_one_attached :image

  validates :name, {presence: true}
  validates :introduction, {presence: true}
  validates :price, {presence: true}
  
  def add_tax_price
    (self.price * 1.1).round
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_details, dependent: :destroy
    has_many :items, through: :order_items
    

    enum payment_method: {credit_card:0, transfer:1}
    enum status: { payment_waiting:0, payment_confirmation:1, in_production:2, preparing_delivery:3, delivered:4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :item
  belongs_to :order
  
  def subtotal
    order_detail * amount
  end


end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
  end

  def create
  end

  def edit
  end

  def update
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    # @items = Item.page(params[:page]).per(10)
    @items = Item.all
    
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    # @item.user_id = current_user.id
    if @item.save!
      redirect_to admin_items_path(@item)
    else
      render "new"
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
      if @item.update(item_params)
        redirect_to admin_item_path(@item.id)
      else
        render "edit"
      end
  end

    private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/orders_status_helper.rb
module Admin::OrdersStatusHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <body style="background-color:ivory;">
    <title>Dogcafe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <h3 class="logo">
            <%= link_to "dogcafe", root_path, class: 'nav-link text-dark' %></h3>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
              aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <!--顧客側-->
              <% if customer_signed_in? %>
                  <p>ようこそ、<%= current_customer.first_name %>さん！</p>
                  <li><%= link_to "マイページ", public_customers_path, class: 'nav-link text-dark' %></li><!--マイページへのリンク-->
                  <li><%= link_to "キャスト紹介", public_items_path, class: 'nav-link text-dark' %></li><!--商品一覧へのリンク-->
                  <li><%= link_to "商品一覧", public_cart_items_path, class: 'nav-link text-dark' %></li><!--カートへのリンク-->
                  <li><%= link_to "ログアウト", destroy_customer_session_path, class: 'nav-link text-dark', method: :delete %></li><!--ログアウトへのリンク-->

              <% elsif admin_signed_in? %>
                  <li><%= link_to "キャスト紹介", admin_items_path, class: 'nav-link text-dark' %></li><!--商品一覧リンク-->
                  <li><%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-dark' %></li><!--会員一覧リンク-->
                  <li><%= link_to "注文履歴一覧", admin_path, class: 'nav-link text-dark' %></li><!--注文履歴一覧リンク-->
                  <li><%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link text-dark' %></li><!--ジャンル一覧リンク-->
                  <li><%= link_to "ログアウト", destroy_admin_session_path, class: 'nav-link text-dark', method: :delete %></li>

              <% else %>
                  <li><%= link_to "About", about_path, 'data-turbolinks': false, class: 'nav-link text-dark' %></li><!--aboutリンク-->
                  <li><%= link_to "キャスト", public_items_path, class: 'nav-link text-dark' %></li><!--商品一覧リンク-->
                  <li><%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark' %></li><!--新規登録リンク-->
                  <li><%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-dark' %></li><!--ログイン画面リンク-->
              <% end %>

            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
    <footer>
    </footer>
  </body>
</html>